### ISSUE TITLE
Cut new release 0.8.0 tarball

### ISSUE THREAD

**Issue by ghost** [OpenChemistry/molequeue#3]
We wish to use molequeue in Gentoo. The current 0.7.1 release is marred with issues due to the bundled Qt5 JSON library clashing with installed Qt5 headers. In addition, for 0.7.1, the library is not compatible Qt5, only Qt4. For 0.8.0 you have ported the library to Qt5. Could you please cut a tarball of the source for us and place it on Sourceforge, seeing you have 0.8.0 Windows Installer at Sourceforge. Thanks a lot!

**Comment by ghost** [comment]
Sorry, excuse my ignorance, I missed the releases page on github.

**Comment by cryos** [comment]
Please let me know if you hit any issues.
