### ISSUE TITLE
At least three files have Python syntax errors

### ISSUE THREAD

**Issue by cclauss** [OpenChemistry/molequeue#30]
$ `flake8 . --count --select=E9,F63,F7 --show-source --statistics`
```
./molequeue/python/test/clienttest.py:24:11: E999 SyntaxError: invalid syntax
    print "MoleQueue ID: ", molequeue_id
          ^
./molequeue/molequeue/app/testing/scripts/submitJob.py:19:11: E999 SyntaxError: invalid syntax
    print "Client %s connecting to socket: %s"%(clientId, socketname)
          ^
./molequeue/molequeue/app/testing/scripts/sendRpcKill.py:13:11: E999 SyntaxError: invalid syntax
    print "Connecting to socket: %s"%socketname
          ^
3     E999 SyntaxError: invalid syntax
3
```

**Comment by Vanshika-Aggarwal** [comment]
Is this file running in Python 3, that would cause a syntax error?

**Comment by Vanshika-Aggarwal** [comment]
i would like to work on this issue

**Comment by adityaomar3** [comment]
I have rectified syntax errors in the files can checkout @ https://github.com/OpenChemistry/molequeue/pull/34#issue-1888731444 please review on it @cclauss , also I am interested in contributing further can somebody help me with discourse form discord or anything

**Comment by ghutchis** [comment]
@adityaomar3 (and everyone) - the project was pretty much abandoned by the previous developers. I've been a bit busy with Avogadro tasks, but will see what I can do to resurrect this in the near future.
